// <auto-generated />
using System;
using HospitalizacionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalizacionAPI.Migrations
{
    [DbContext(typeof(HospitalizacionDbContext))]
    [Migration("20260503152003_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalizacionAPI.Models.Admision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CamaCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PacienteCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CamaCodigo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PacienteCodigo");

                    b.ToTable("Admisiones");
                });

            modelBuilder.Entity("HospitalizacionAPI.Models.Cama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Camas");
                });

            modelBuilder.Entity("HospitalizacionAPI.Models.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("HospitalizacionAPI.Models.Tratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdmisionCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreMedicamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdmisionCodigo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("HospitalizacionAPI.Models.Admision", b =>
                {
                    b.HasOne("HospitalizacionAPI.Models.Cama", "Cama")
                        .WithMany()
                        .HasForeignKey("CamaCodigo")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalizacionAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteCodigo")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cama");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HospitalizacionAPI.Models.Tratamiento", b =>
                {
                    b.HasOne("HospitalizacionAPI.Models.Admision", "Admision")
                        .WithMany()
                        .HasForeignKey("AdmisionCodigo")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admision");
                });
#pragma warning restore 612, 618
        }
    }
}
